server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://rm-bp19kpi6407glu0290o.mysql.rds.aliyuncs.com:3306/sxrongcarloan?useUnicode=true&characterEncoding=utf-8
    username: sxrongp2p
    password: sxRong@1103
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath:mapper/*.xml
